version: "3"
services:
  reverseproxy:
      image: aronanubhav/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-feed
        - backend-user
  backend-user:
    image: aronanubhav/udacity-restapi-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: aronanubhav
      POSTGRES_PASSWORD: Covid2020
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: aronanubhav.cjzgfj3nh7rd.eu-west-1.rds.amazonaws.com
      AWS_REGION: eu-west-1
      AWS_PROFILE: default
      AWS_MEDIA_BUCKET: s3-aronanubhav-dev
      JWT_TOKEN: hello
      URL: "http://localhost:8080"
  backend-feed:
    image: aronanubhav/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: aronanubhav
      POSTGRES_PASSWORD: Covid2020
      POSTGRES_DB: postgres
      POSTGRES_HOST: aronanubhav.cjzgfj3nh7rd.eu-west-1.rds.amazonaws.com
      AWS_REGION: eu-west-1
      AWS_PROFILE: default
      AWS_MEDIA_BUCKET: s3-aronanubhav-dev
      JWT_TOKEN: hello
      URL: "http://localhost:8080"
  frontend:
    image: aronanubhav/udacity-frontend
    ports:
      - "8080:80"
