apiVersion: v1
kind: Service
metadata:
  labels:
    service: udacity-restapi-feed
  name: udacity-restapi-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udacity-restapi-feed
