apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-frontend
  labels:
    app: udacity-frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: udacity-frontend
  template:
    metadata:
      labels:
        app: udacity-frontend
    spec:
      containers:
      - name: udacity-frontend
        image: aronanubhav/udacity-frontend
        resources:
          limits:
            cpu: "1.5"
          requests:
            cpu: "500m"
        ports:
        - containerPort: 8100
        livenessProbe:
          httpGet:
            path: /health
            port: 8100
          initialDelaySeconds: 3
          periodSeconds: 3
