apiVersion: apps/v1
kind: Deployment
metadata:
        name: reverseproxy
spec:
  replicas: 5
  selector:
          matchLabels:
                  app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: aronanubhav/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
          initialDelaySeconds: 3
          periodSeconds: 300000
